name: Check for JSON duplicates
on: [push]

jobs:
  opa_eval:
    runs-on: ubuntu-latest
    name: Open Policy Agent
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Evaluate OPA Policy w/tags
      id: opa_eval_tags
      uses: migara/test-action@master
      with:
        tests: ./validate/opa/panos.rego
        policy: ./examples/files/json/tags.json,./examples/files/json/iron_skillet/tags.json #path to tags file

    - name: Print Results tags
      run: |
       echo $opa_results | jq -r '.result[].expressions[].value'
      env:
       opa_results: ${{ steps.opa_eval_tags.outputs.opa_results }}

    - name: Evaluate OPA Policy w/addr_obj
      id: opa_eval_addr_obj
      uses: migara/test-action@master
      with:
        tests: ./validate/opa/panos.rego
        policy: ./examples/files/json/addr_obj.json #path to address objects file

    - name: Print Results addr_obj
      run: |
       echo $opa_results | jq -r '.result[].expressions[].value'
      env:
       opa_results: ${{ steps.opa_eval_addr_obj.outputs.opa_results }}

    - name: Evaluate OPA Policy w/addr_group
      id: opa_eval_addr_group
      uses: migara/test-action@master
      with:
        tests: ./validate/opa/panos.rego
        policy: ./examples/files/json/addr_group.json #path to address groups file

    - name: Print Results addr_group
      run: |
       echo $opa_results | jq -r '.result[].expressions[].value'
      env:
       opa_results: ${{ steps.opa_eval_addr_group.outputs.opa_results }}

    - name: Evaluate OPA Policy w/NAT
      id: opa_eval_NAT
      uses: migara/test-action@master
      with:
        tests: ./validate/opa/panos.rego
        policy: ./examples/files/json/nat.json #path to nat security policy file

    - name: Print Results nat
      run: |
       echo $opa_results | jq -r '.result[].expressions[].value'
      env:
       opa_results: ${{ steps.opa_eval_NAT.outputs.opa_results }}

    - name: Evaluate OPA Policy w/sec_ex
      id: opa_eval_sec_ex
      uses: migara/test-action@master
      with:
        tests: ./validate/opa/panos.rego
        policy: ./examples/files/json/sec_policy.json #path to security policy file

    - name: Print Results sec_ex
      run: |
       echo $opa_results | jq -r '.result[].expressions[].value'
      env:
       opa_results: ${{ steps.opa_eval_sec_ex.outputs.opa_results }}

    - name: Evaluate OPA Policy w/sevices
      id: opa_eval_service
      uses: migara/test-action@master
      with:
        tests: ./validate/opa/panos.rego
        policy: ./examples/files/json/services.json #path to services file

    - name: Print Results services
      run: |
       echo $opa_results | jq -r '.result[].expressions[].value'
      env:
       opa_results: ${{ steps.opa_eval_service.outputs.opa_results }}
