name: Validate JSONs

on: [pull_request, push]

jobs:
  verify-json-validation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Validate tags JSON
        uses: nhalstead/validate-json-action@0.1.3
        with:
          schema: ./validate/schemas/tags_schema.json
          jsons: ./examples/files/json/tags.json #path to tags file

      - name: Validate address objects JSON
        uses: nhalstead/validate-json-action@0.1.3
        with:
          schema: ./validate/schemas/addr_obj_schema.json
          jsons: ./examples/files/json/addr_obj.json #path to address objects file

      - name: Validate address group JSON
        uses: nhalstead/validate-json-action@0.1.3
        with:
          schema: ./validate/schemas/addr_group_schema.json
          jsons: ./examples/files/json/addr_group.json #path to address groups file

      - name: Validate nat JSON
        uses: nhalstead/validate-json-action@0.1.3
        with:
          schema: ./validate/schemas/NAT_schema.json
          jsons: ./examples/files/json/nat.json #path to NAT policy file

      - name: Validate security policy JSON
        uses: nhalstead/validate-json-action@0.1.3
        with:
          schema: ./validate/schemas/sec_policy_schema.json
          jsons: ./examples/files/json/sec_policy.json,./examples/files/json/sec_policy_demo.json  #path to security policy file

      - name: Validate services JSON
        uses: nhalstead/validate-json-action@0.1.3
        with:
          schema: ./validate/schemas/services_schema.json
          jsons: ./examples/files/json/services.json #path to services file
